import { jsPDF } from 'jspdf';

export interface DocumentData {
  type: 'FIR' | 'RTI' | 'explanation';
  content: string;
  userDetails?: {
    name?: string;
    address?: string;
    phone?: string;
  };
  language?: string;
  title?: string;
}

export const generatePDF = (data: DocumentData): jsPDF => {
  const doc = new jsPDF();
  
  // Set font (basic fonts that support ASCII characters)
  doc.setFont('helvetica');
  
  // Header
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  
  const headerText = data.type === 'explanation' ? 
    (data.title || 'Document Explanation') :
    data.type === 'FIR' ? 
    (data.language === 'hi' ? 'प्राथमिकी रिपोर्ट (FIR)' : 
     data.language === 'te' ? 'ప్రాథమిక నివేదిక (FIR)' :
     data.language === 'mr' ? 'प्राथमिक अहवाल (FIR)' :
     data.language === 'kn' ? 'ಪ್ರಾಥಮಿಕ ಮಾಹಿತಿ ವರದಿ (FIR)' :
     'First Information Report (FIR)') :
    (data.language === 'hi' ? 'सूचना का अधिकार आवेदन (RTI)' :
     data.language === 'te' ? 'సమాచార హక్కు దరఖాస్తు (RTI)' :
     data.language === 'mr' ? 'माहिती अधिकार अर्ज (RTI)' :
     data.language === 'kn' ? 'ಮಾಹಿತಿ ಹಕ್ಕು ಅರ್ಜಿ (RTI)' :
     'Right to Information Application (RTI)');
  
  doc.text(headerText, 20, 30);
  
  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const date = new Date().toLocaleDateString();
  doc.text(`Date: ${date}`, 20, 45);
  
  // Content
  doc.setFontSize(12);
  const lines = doc.splitTextToSize(data.content, 170);
  doc.text(lines, 20, 60);
  
  // User details if provided
  if (data.userDetails) {
    const yPosition = 60 + (lines.length * 5) + 20;
    
    doc.setFont('helvetica', 'bold');
    doc.text('Applicant Details:', 20, yPosition);
    
    doc.setFont('helvetica', 'normal');
    let currentY = yPosition + 10;
    
    if (data.userDetails.name) {
      doc.text(`Name: ${data.userDetails.name}`, 20, currentY);
      currentY += 10;
    }
    
    if (data.userDetails.address) {
      const addressLines = doc.splitTextToSize(`Address: ${data.userDetails.address}`, 170);
      doc.text(addressLines, 20, currentY);
      currentY += addressLines.length * 5 + 5;
    }
    
    if (data.userDetails.phone) {
      doc.text(`Phone: ${data.userDetails.phone}`, 20, currentY);
    }
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Legislate AI - Legal Assistant', 20, 280);
  
  return doc;
};

export const downloadPDF = (data: DocumentData, filename?: string) => {
  const doc = generatePDF(data);
  const defaultFilename = `${data.type}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename || defaultFilename);
};

export const sharePDFOnWhatsApp = (data: DocumentData) => {
  // Create a simplified text version for WhatsApp sharing
  const headerText = data.type === 'FIR' ? 
    (data.language === 'hi' ? '🏛️ प्राथमिकी रिपोर्ट (FIR)\n' : 
     data.language === 'te' ? '🏛️ ప్రాథమిక నివేదిక (FIR)\n' :
     data.language === 'mr' ? '🏛️ प्राथमिक अहवाल (FIR)\n' :
     data.language === 'kn' ? '🏛️ ಪ್ರಾಥಮಿಕ ಮಾಹಿತಿ ವರದಿ (FIR)\n' :
     '🏛️ First Information Report (FIR)\n') :
    (data.language === 'hi' ? '📋 सूचना का अधिकार आवेदन (RTI)\n' :
     data.language === 'te' ? '📋 సమాచార హక్కు దరఖాస్తు (RTI)\n' :
     data.language === 'mr' ? '📋 माहिती अधिकार अर्ज (RTI)\n' :
     data.language === 'kn' ? '📋 ಮಾಹಿತಿ ಹಕ್ಕು ಅರ್ಜಿ (RTI)\n' :
     '📋 Right to Information Application (RTI)\n');
  
  const message = `${headerText}\n📅 Date: ${new Date().toLocaleDateString()}\n\n${data.content}\n\n⚖️ Generated by Legislate AI Legal Assistant`;
  
  const encodedMessage = encodeURIComponent(message);
  const whatsappUrl = `https://wa.me/?text=${encodedMessage}`;
  
  window.open(whatsappUrl, '_blank');
};